"""Public router contract manifest for Albucore verification tooling."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from tests.verification_constants import (
    DTYPE_FLOAT32,
    DTYPE_FLOAT64,
    DTYPE_OTHER_NUMERIC_FALLBACK,
    DTYPE_UINT8,
    HWC_XHWC_NDHWC,
    IMAGE_CHANNELS,
    IMAGE_DTYPES,
    CHANNEL_1,
    CHANNEL_3,
    CHANNEL_4,
    LAYOUT_2D,
    LAYOUT_HWC,
    LAYOUT_POINTS,
    SCALAR_VECTOR_ARRAY,
    VALUE_ALPHA,
    VALUE_BETA,
    VALUE_BIAS,
    VALUE_BORDER_MODE,
    VALUE_BORDER_SIZES,
    VALUE_BORDER_VALUE,
    VALUE_DENOMINATOR,
    VALUE_DSIZE,
    VALUE_EPS,
    VALUE_EXPLICIT_AXIS,
    VALUE_FACTOR,
    VALUE_GAMMA,
    VALUE_GLOBAL_AXIS,
    VALUE_IMAGE_ARRAY,
    VALUE_INTERPOLATION,
    VALUE_KERNEL_SIZE,
    VALUE_MAP_X,
    VALUE_MAP_Y,
    VALUE_MATRIX,
    VALUE_MATRIX_A,
    VALUE_MATRIX_B,
    VALUE_MAX_VALUE,
    VALUE_MEAN,
    VALUE_NORMALIZATION_MODE,
    VALUE_PER_CHANNEL_AXIS,
    VALUE_PER_CHANNEL_EXPONENT,
    VALUE_PER_CHANNEL_LUT,
    VALUE_PER_CHANNEL_VECTOR,
    VALUE_POINTS_A,
    VALUE_POINTS_B,
    VALUE_SCALAR,
    VALUE_SCALAR_EXPONENT,
    VALUE_SECOND_IMAGE,
    VALUE_SHARED_LUT,
    VALUE_TARGET_DTYPE,
    ChannelSpec,
    DTypeName,
    LayoutName,
    ValueKind,
)


RouterKind = Literal["function", "decorator", "geometric"]


@dataclass(frozen=True)
class RouterContract:
    """Declarative contract metadata for one public router."""

    name: str
    kind: RouterKind
    dtypes: tuple[DTypeName, ...]
    layouts: tuple[LayoutName, ...]
    channels: tuple[ChannelSpec, ...]
    values: tuple[ValueKind, ...]
    output_shape: str
    output_dtype: str
    aliasing: str
    reference: str
    benchmark_names: tuple[str, ...] = ()
    release_blocking_performance: bool = False


ROUTER_CONTRACTS: dict[str, RouterContract] = {
    "add": RouterContract(
        name="add",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=SCALAR_VECTOR_ARRAY,
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="inplace parameter controls mutation; add 0 may return input",
        reference="clip(img + value)",
        benchmark_names=("add",),
        release_blocking_performance=True,
    ),
    "add_array": RouterContract(
        name="add_array",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_IMAGE_ARRAY,),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="inplace parameter controls mutation",
        reference="clip(img + value_array)",
        benchmark_names=("add_array",),
        release_blocking_performance=True,
    ),
    "add_constant": RouterContract(
        name="add_constant",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_SCALAR,),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="inplace parameter controls mutation",
        reference="clip(img + scalar)",
        benchmark_names=("add_constant",),
    ),
    "add_vector": RouterContract(
        name="add_vector",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_PER_CHANNEL_VECTOR,),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="inplace parameter controls mutation",
        reference="clip(img + per_channel_vector)",
        benchmark_names=("add_vector",),
        release_blocking_performance=True,
    ),
    "add_weighted": RouterContract(
        name="add_weighted",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_SECOND_IMAGE, VALUE_ALPHA, VALUE_BETA, VALUE_GAMMA),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="does not mutate inputs",
        reference="clip(img1 * alpha + img2 * beta + gamma)",
        benchmark_names=("add_weighted",),
        release_blocking_performance=True,
    ),
    "apply_uint8_lut": RouterContract(
        name="apply_uint8_lut",
        kind="function",
        dtypes=(DTYPE_UINT8,),
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_SHARED_LUT, VALUE_PER_CHANNEL_LUT),
        output_shape="same as input",
        output_dtype="lut dtype",
        aliasing="inplace parameter controls mutation when supported",
        reference="OpenCV-compatible uint8 lookup",
        benchmark_names=("apply_uint8_lut",),
        release_blocking_performance=True,
    ),
    "float32_io": RouterContract(
        name="float32_io",
        kind="decorator",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(),
        output_shape="wrapped function contract",
        output_dtype="float32 during wrapped call; restored per decorator contract",
        aliasing="wrapped function contract",
        reference="decorator conversion contract",
    ),
    "from_float": RouterContract(
        name="from_float",
        kind="function",
        dtypes=(DTYPE_FLOAT32,),
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_TARGET_DTYPE,),
        output_shape="same as input",
        output_dtype="target dtype",
        aliasing="does not mutate input",
        reference="scale from [0, 1] float to target dtype range",
        benchmark_names=("from_float",),
        release_blocking_performance=True,
    ),
    "hflip": RouterContract(
        name="hflip",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=(LAYOUT_HWC,),
        channels=IMAGE_CHANNELS,
        values=(),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="does not mutate input",
        reference="img[:, ::-1, ...]",
        benchmark_names=("hflip",),
        release_blocking_performance=True,
    ),
    "matmul": RouterContract(
        name="matmul",
        kind="function",
        dtypes=(DTYPE_FLOAT32, DTYPE_FLOAT64),
        layouts=(LAYOUT_2D,),
        channels=(),
        values=(VALUE_MATRIX_A, VALUE_MATRIX_B),
        output_shape="matrix product shape",
        output_dtype="NumPy matmul dtype",
        aliasing="does not mutate inputs",
        reference="numpy.matmul",
        benchmark_names=("matmul",),
    ),
    "mean": RouterContract(
        name="mean",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_GLOBAL_AXIS, VALUE_PER_CHANNEL_AXIS),
        output_shape="scalar/keepdims or per-channel shape",
        output_dtype="float64 accumulator",
        aliasing="does not mutate input",
        reference="numpy.mean with documented accumulator semantics",
        benchmark_names=("mean", "mean_per_channel"),
        release_blocking_performance=True,
    ),
    "mean_std": RouterContract(
        name="mean_std",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_GLOBAL_AXIS, VALUE_PER_CHANNEL_AXIS, VALUE_EPS),
        output_shape="scalar/keepdims or per-channel shape pair",
        output_dtype="float64 accumulator",
        aliasing="does not mutate input",
        reference="numpy.mean/std with documented accumulator semantics",
        benchmark_names=("mean_std", "mean_std_per_channel"),
        release_blocking_performance=True,
    ),
    "median_blur": RouterContract(
        name="median_blur",
        kind="function",
        dtypes=(DTYPE_UINT8,),
        layouts=(LAYOUT_HWC,),
        channels=(CHANNEL_1, CHANNEL_3, CHANNEL_4),
        values=(VALUE_KERNEL_SIZE,),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="does not mutate input",
        reference="cv2.medianBlur with channel preservation",
        benchmark_names=("median_blur",),
    ),
    "multiply": RouterContract(
        name="multiply",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=SCALAR_VECTOR_ARRAY,
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="inplace parameter controls mutation; multiply by 1 may return input",
        reference="clip(img * value)",
        benchmark_names=("multiply",),
        release_blocking_performance=True,
    ),
    "multiply_add": RouterContract(
        name="multiply_add",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_FACTOR, VALUE_BIAS),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="does not mutate input unless documented",
        reference="clip(img * factor + bias)",
        benchmark_names=("multiply_add",),
        release_blocking_performance=True,
    ),
    "multiply_by_array": RouterContract(
        name="multiply_by_array",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_IMAGE_ARRAY,),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="inplace parameter controls mutation",
        reference="clip(img * value_array)",
        benchmark_names=("multiply_by_array",),
        release_blocking_performance=True,
    ),
    "multiply_by_constant": RouterContract(
        name="multiply_by_constant",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_SCALAR,),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="inplace parameter controls mutation",
        reference="clip(img * scalar)",
        benchmark_names=("multiply_by_constant",),
    ),
    "multiply_by_vector": RouterContract(
        name="multiply_by_vector",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_PER_CHANNEL_VECTOR,),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="inplace parameter controls mutation",
        reference="clip(img * per_channel_vector)",
        benchmark_names=("multiply_by_vector",),
        release_blocking_performance=True,
    ),
    "normalize": RouterContract(
        name="normalize",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_MEAN, VALUE_DENOMINATOR),
        output_shape="same as input",
        output_dtype="float32",
        aliasing="does not mutate input unless documented",
        reference="(img - mean) * denominator",
        benchmark_names=("normalize",),
        release_blocking_performance=True,
    ),
    "normalize_per_image": RouterContract(
        name="normalize_per_image",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_NORMALIZATION_MODE,),
        output_shape="same as input",
        output_dtype="float32",
        aliasing="does not mutate input unless documented",
        reference="mode-specific per-image normalization formula",
        benchmark_names=("normalize_per_image",),
        release_blocking_performance=True,
    ),
    "pairwise_distances_squared": RouterContract(
        name="pairwise_distances_squared",
        kind="function",
        dtypes=(DTYPE_FLOAT32, DTYPE_FLOAT64),
        layouts=(LAYOUT_POINTS,),
        channels=(),
        values=(VALUE_POINTS_A, VALUE_POINTS_B),
        output_shape="(len(points_a), len(points_b))",
        output_dtype="floating",
        aliasing="does not mutate inputs",
        reference="squared Euclidean distance matrix",
        benchmark_names=("pairwise_distances_squared",),
    ),
    "power": RouterContract(
        name="power",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_SCALAR_EXPONENT, VALUE_PER_CHANNEL_EXPONENT),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="does not mutate input unless documented",
        reference="clip(img ** exponent)",
        benchmark_names=("power",),
    ),
    "reduce_sum": RouterContract(
        name="reduce_sum",
        kind="function",
        dtypes=(DTYPE_UINT8, DTYPE_FLOAT32, DTYPE_OTHER_NUMERIC_FALLBACK),
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_GLOBAL_AXIS, VALUE_PER_CHANNEL_AXIS, VALUE_EXPLICIT_AXIS),
        output_shape="scalar/keepdims or reduced-axis shape",
        output_dtype="uint64/int64/float64 accumulator",
        aliasing="does not mutate input",
        reference="numpy.sum with documented accumulator semantics",
        benchmark_names=("reduce_sum", "reduce_sum_per_channel"),
        release_blocking_performance=True,
    ),
    "std": RouterContract(
        name="std",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_GLOBAL_AXIS, VALUE_PER_CHANNEL_AXIS, VALUE_EPS),
        output_shape="scalar/keepdims or per-channel shape",
        output_dtype="float64 accumulator",
        aliasing="does not mutate input",
        reference="numpy.std with documented accumulator semantics",
        benchmark_names=("std", "std_per_channel"),
        release_blocking_performance=True,
    ),
    "sz_lut": RouterContract(
        name="sz_lut",
        kind="function",
        dtypes=(DTYPE_UINT8,),
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_SHARED_LUT, VALUE_PER_CHANNEL_LUT),
        output_shape="same as input",
        output_dtype="lut dtype",
        aliasing="inplace by default on provided buffer",
        reference="StringZilla/OpenCV-compatible uint8 lookup",
        benchmark_names=("sz_lut",),
        release_blocking_performance=True,
    ),
    "to_float": RouterContract(
        name="to_float",
        kind="function",
        dtypes=(DTYPE_UINT8,),
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(VALUE_MAX_VALUE,),
        output_shape="same as input",
        output_dtype="float32",
        aliasing="does not mutate input",
        reference="scale integer image to [0, 1] float32",
        benchmark_names=("to_float",),
        release_blocking_performance=True,
    ),
    "uint8_io": RouterContract(
        name="uint8_io",
        kind="decorator",
        dtypes=IMAGE_DTYPES,
        layouts=HWC_XHWC_NDHWC,
        channels=IMAGE_CHANNELS,
        values=(),
        output_shape="wrapped function contract",
        output_dtype="uint8 during wrapped call; restored per decorator contract",
        aliasing="wrapped function contract",
        reference="decorator conversion contract",
    ),
    "vflip": RouterContract(
        name="vflip",
        kind="function",
        dtypes=IMAGE_DTYPES,
        layouts=(LAYOUT_HWC,),
        channels=IMAGE_CHANNELS,
        values=(),
        output_shape="same as input",
        output_dtype="same as input",
        aliasing="does not mutate input",
        reference="img[::-1, :, ...]",
        benchmark_names=("vflip",),
        release_blocking_performance=True,
    ),
    "copy_make_border": RouterContract(
        name="copy_make_border",
        kind="geometric",
        dtypes=IMAGE_DTYPES,
        layouts=(LAYOUT_HWC,),
        channels=IMAGE_CHANNELS,
        values=(VALUE_BORDER_SIZES, VALUE_BORDER_MODE, VALUE_BORDER_VALUE),
        output_shape="input H/W plus requested border; same channels",
        output_dtype="same as input",
        aliasing="does not mutate input unless dst aliases explicitly",
        reference="cv2.copyMakeBorder with >4-channel support",
        benchmark_names=("copy_make_border",),
    ),
    "remap": RouterContract(
        name="remap",
        kind="geometric",
        dtypes=IMAGE_DTYPES,
        layouts=(LAYOUT_HWC,),
        channels=IMAGE_CHANNELS,
        values=(VALUE_MAP_X, VALUE_MAP_Y, VALUE_INTERPOLATION, VALUE_BORDER_MODE, VALUE_BORDER_VALUE),
        output_shape="map shape plus input channels",
        output_dtype="same as input",
        aliasing="does not mutate input unless dst aliases explicitly",
        reference="cv2.remap with channel preservation and chunking",
        benchmark_names=("remap",),
        release_blocking_performance=True,
    ),
    "resize": RouterContract(
        name="resize",
        kind="geometric",
        dtypes=IMAGE_DTYPES,
        layouts=(LAYOUT_HWC,),
        channels=IMAGE_CHANNELS,
        values=(VALUE_DSIZE, VALUE_INTERPOLATION),
        output_shape="requested H/W plus input channels",
        output_dtype="same as input",
        aliasing="does not mutate input",
        reference="cv2.resize with channel preservation",
        benchmark_names=("resize",),
        release_blocking_performance=True,
    ),
    "warp_affine": RouterContract(
        name="warp_affine",
        kind="geometric",
        dtypes=IMAGE_DTYPES,
        layouts=(LAYOUT_HWC,),
        channels=IMAGE_CHANNELS,
        values=(VALUE_MATRIX, VALUE_DSIZE, VALUE_INTERPOLATION, VALUE_BORDER_MODE, VALUE_BORDER_VALUE),
        output_shape="dsize height/width plus input channels",
        output_dtype="same as input",
        aliasing="does not mutate input unless dst aliases explicitly",
        reference="cv2.warpAffine with channel preservation and chunking",
        benchmark_names=("warp_affine",),
    ),
    "warp_perspective": RouterContract(
        name="warp_perspective",
        kind="geometric",
        dtypes=IMAGE_DTYPES,
        layouts=(LAYOUT_HWC,),
        channels=IMAGE_CHANNELS,
        values=(VALUE_MATRIX, VALUE_DSIZE, VALUE_INTERPOLATION, VALUE_BORDER_MODE, VALUE_BORDER_VALUE),
        output_shape="dsize height/width plus input channels",
        output_dtype="same as input",
        aliasing="does not mutate input unless dst aliases explicitly",
        reference="cv2.warpPerspective with channel preservation and chunking",
        benchmark_names=("warp_perspective",),
    ),
}


FUNCTION_CONTRACTS = {
    name: contract for name, contract in ROUTER_CONTRACTS.items() if contract.kind in {"function", "decorator"}
}
GEOMETRIC_CONTRACTS = {name: contract for name, contract in ROUTER_CONTRACTS.items() if contract.kind == "geometric"}
